name: Cypress tests
on:
  push:
  repository_dispatch:
    types: [on-client-build, on-server-build]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    services:
      test-server:
        image: blocknotes/test_rails7
        # env:
        #   VERBOSE_LOGS: 1
        options: >-
          --health-cmd "nc -z localhost 3000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3000:3000

      test-client:
        image: blocknotes/test_alpinejs
        options: >-
          --health-cmd "nc -z localhost 8000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          BROWSERSLIST_IGNORE_OLD_DATA: 1

      - name: On failure, store screenshots 
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # - name: On failure, store videos 
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
